### ISSUE TITLE
Git Setup not validating email domain via internet

### ISSUE THREAD

**Issue by jamesover** [lordkator/ZonamaDev#165]
Git Setup not validating email domain via internet.  Internet up and working but unable to get past this part. Did not have any errors during install and set till this.

Thanking you in advance

**Comment by lordkator** [comment]
the fastest way to get help for that would be to try the #emuyoda  or
#opendev channels in IRC

-k

On Jun 7, 2016, at 06:36, jamesover <notifications@github.com> wrote:

Git Setup not validating email domain via internet. Internet up and working
but unable to get past this part. Did not have any errors during install
and set till this.

Thanking you in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lordkator/ZonamaDev/issues/165>, or mute the thread
<https://github.com/notifications/unsubscribe/AJtOrUxdwkz1Bu8MvJg2b7TFFDmtls2wks5qJQN1gaJpZM4Ivkzc>
.

**Comment by jamesover** [comment]
I did that yesterday. And was told to open a ticket here. But I will go back and try again...

Sent from my iPhone

On Jun 7, 2016, at 7:12 AM, lordkator <notifications@github.com<mailto:notifications@github.com>> wrote:

the fastest way to get help for that would be to try the #emuyoda or
#opendev channels in IRC

-k

On Jun 7, 2016, at 06:36, jamesover <notifications@github.com<mailto:notifications@github.com>> wrote:

Git Setup not validating email domain via internet. Internet up and working
but unable to get past this part. Did not have any errors during install
and set till this.

Thanking you in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lordkator/ZonamaDev/issues/165>, or mute the thread
<https://github.com/notifications/unsubscribe/AJtOrUxdwkz1Bu8MvJg2b7TFFDmtls2wks5qJQN1gaJpZM4Ivkzc>
.

**Comment by karlbunch** [comment]
Please post screen shots of the errors you are getting, 99% of the time this is related to internet issues or you have a typo in your domain name.

**Comment by eysho** [comment]
HAve a question is the Emuyoda the WEb projekt not publik ?

**Comment by karlbunch** [comment]
Yes its all here in this repo, nothing is missing, I'm not sure why you asked?

**Comment by eysho** [comment]
Das ein Auto Replay Script. Wenn ich Zeit habe antworte ich.

**Comment by eysho** [comment]
My question is to the web part can you drope me a email on eysho@bkg.me ?
